# Eight Queens Puzzle
The problem of placing eight chess queens on an 8×8 chessboard so that no two queens threaten each other. Thus, a solution requires that no two queens share the same row, column, or diagonal. 

In [12]:
import numpy as np

In [13]:
N = 8
cache = {}
board = np.zeros(((N, N)), np.int8)
print(board)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [14]:
# Converting matrix to sting to store it as cache
def convert_to_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string +=str(board[i][j])
    return board_string

In [15]:
convert_to_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [16]:
# Check if the board alignes with the rules
def safety(board):
    board_key = convert_to_string(board)
    
    if board_key in cache:
        print('Using cache')
        return cache[board_key]
    
    # Check if there is no more than one queen on the same row 
    row_sum = np.sum(board, axis = 1)
    if len(row_sum[np.where(row_sum > 1)]) > 0:
        cache[board_key] = False
        return False
    
    # Check if there is no more than one queen on the same column
    col_sum = np.sum(board, axis = 0)
    if len(col_sum[np.where(col_sum > 1)]) > 0:
        cache[board_key] = False
        return False
        
    # Check if there is no more than one queen on the same diagonal
    diags = [board[::-1, :].diagonal(i) for i in range(-board.shape[0]+1,board.shape[1])]

    diags.extend(board.diagonal(i) for i in range(board.shape[1] - 1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag) > 1:
            cache[board_key] = False
            return False
        
    cache[board_key] = True
    
    return True

In [17]:
board_copy = board.copy()
board_copy[0][0] = 1
board_copy[7][7] = 1
print(board_copy)
safety(board_copy)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]


False

In [18]:
def place_queen(board, column):
    if column >= N:
        return True
    for row in range(N):
        board[row][column] = 1
        
        safe = False
        if safety(board):
            safe = place_queen(board, column + 1)
            
        if not safe:
            board[row][column] = 0
        else:
            break
            
    return safe

In [19]:
cache

{'1000000000000000000000000000000000000000000000000000000000000001': False}

In [20]:
board = np.zeros((N, N), np.int8)
result = place_queen(board, 0)
print(result)

True


In [21]:
print(board)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


In [22]:
cache

{'1000000000000000000000000000000000000000000000000000000000000001': False,
 '1000000000000000000000000000000000000000000000000000000000000000': True,
 '1100000000000000000000000000000000000000000000000000000000000000': False,
 '1000000001000000000000000000000000000000000000000000000000000000': False,
 '1000000000000000010000000000000000000000000000000000000000000000': True,
 '1010000000000000010000000000000000000000000000000000000000000000': False,
 '1000000000100000010000000000000000000000000000000000000000000000': False,
 '1000000000000000011000000000000000000000000000000000000000000000': False,
 '1000000000000000010000000010000000000000000000000000000000000000': False,
 '1000000000000000010000000000000000100000000000000000000000000000': True,
 '1001000000000000010000000000000000100000000000000000000000000000': False,
 '1000000000010000010000000000000000100000000000000000000000000000': True,
 '1000100000010000010000000000000000100000000000000000000000000000': False,
 '10000000000110